[package]
name = "wasserxr"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "wasserxr-macros"]
resolver = "3"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
libc = "0.2.186"
log = "0.4.32"
serde = { version = "1.0.228", features = ["derive"] }
wasserxr-macros = { path = "wasserxr-macros" }
uuid = { version = "1.23.2", features = ["serde", "v7"] }
chrono = "0.4.45"

[build-dependencies]
cbindgen = "0.29"

[lib]
crate-type = ["staticlib", "rlib"]
