[package]
name    = "wasserxr-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary     = { version = "1", features = ["derive"] }
libfuzzer-sys = "0.4"
wasserxr      = { path = ".." }

[workspace]
members = ["."]

[profile.release]
debug-assertions = true

[[bin]]
name  = "basic"
path  = "fuzz_targets/basic.rs"
test  = false
doc   = false
bench = false
